config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :entries, :only => [:show, :new, :create, :edit, :update, :destroy] do
      resources :comments, :only => [:create, :destroy] do
        patch 'approve'
      end
    end
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base

  has_many :entries

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  def status_text_for_approve_link
    if self.status == 'unapproved'
      'Approve'
    else
      ''
    end
  end

  def body_text_depends_on_status
     if self.status == 'approved'
       self.body
     else
       '(承認待ち)'
     end
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]

  def create

    # params = comment_params

    @blog = Blog.find(params[:blog_id])
    @entry = @blog.entries.find(params[:entry_id])
    @comment = Comment.new(comment_params)

    # 作成直後はunapproved
    @comment.status = 'unapproved'

    respond_to do |format|
      if @comment.save

        #コメントが追加された旨のメールを送る
        CommentMailer.comment_add(@blog, @entry, @comment).deliver

        format.html { redirect_to blog_entry_url(@blog, @entry), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    @comment.destroy
    respond_to do |format|
      format.html { redirect_to blog_entry_url(@blog, @entry), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve

    @blog = Blog.find(params[:blog_id])
    @entry = @blog.entries.find(params[:entry_id])
    @comment = @entry.comments.find(params[:comment_id])
    @comment.status = 'approved'

    respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_entry_url(@blog, @entry), notice: 'Comment was approved.' }
        format.json { render :show, status: :ok, location: blog_entry_url(@blog, @entry) }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @blog = Blog.find(params[:blog_id])
      @entry = @blog.entries.find(params[:entry_id])
      @comment = @entry.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :entry_id)
    end

    def blog_id_param
      params.permit(:body, :blog_id, :entry_id)[:blog_id]
    end

    def entry_id_param
      params.permit(:body, :blog_id, :entry_id)[:entry_id]
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    # 新規作成用のコメントオブジェクトを
    @comment = Comment.new
  end

  # GET /entries/new
  def new

    # ブログを取得する
    @blog = Blog.find(blog_id_param)
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create

    @blog = Blog.find(blog_id_param)
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to blog_url(@blog), notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to blog_url(@blog), notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to blog_url(@blog), notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @blog = Blog.find(params[:blog_id])
      @entry = @blog.entries.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body, :blog_id)
    end

    def blog_id_param
      params.permit(:title, :body, :blog_id)[:blog_id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form'

= link_to 'Show', @blog
\|
= link_to 'Back', blogs_path

app/views/blogs/index.html.haml
%h1 Listing blogs

%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @blogs.each do |blog|
      %tr
        %td= blog.title
        %td= link_to 'Show', blog
        %td= link_to 'Edit', edit_blog_path(blog)
        %td= link_to 'Destroy', blog, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Blog', new_blog_path

app/views/blogs/new.html.haml
%h1 New blog

= render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
%p#notice= notice

%h1
  %b Title:
  = @blog.title

= link_to 'Edit', edit_blog_path(@blog)
\|
= link_to 'Back', blogs_path

%hr

%h2 Listing entries

%table
  %thead
    %tr
      %th Title
      %th Body
      %th
      %th
      %th

  %tbody
    - @blog.entries.each do |entry|
      %tr
        %td= entry.title
        %td= entry.body
        %td= link_to 'Show', blog_entry_path(@blog, entry)
        %td= link_to 'Edit', edit_blog_entry_path(@blog, entry)
        %td= link_to 'Destroy', [@blog, entry] , :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Entry', new_blog_entry_path(@blog)

app/views/entries/_form.html.haml
= form_for([@blog, @entry]) do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, "error")} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  = f.hidden_field :blog_id, value: @blog.id
  .actions
    = f.submit 'Save'

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', blog_entry_url(@blog, @entry)
\|
= link_to 'Back', blog_url(@blog)

app/views/entries/new.html.haml
%h1 New entry: #{@blog.title}

= render 'form'

= link_to 'Back', blog_entries_path(@blog)

app/views/entries/show.html.haml
%p#notice= notice

%h1= @blog.title

%p
  %b Title:
  = @entry.title
%p
  %b Body:
  = @entry.body
%p
  %b Blog:
  = @entry.blog_id

= link_to 'Edit', edit_blog_entry_path(@blog, @entry)
\|
= link_to 'Back', blog_path(@blog)

%hr

%h2 Listing comments

%table
  %thead
    %tr
      %th Body
      %th
      %th

  %tbody
    - @entry.comments.each do |comment|
      %tr
        %td= comment.body_text_depends_on_status
        %td= link_to comment.status_text_for_approve_link, blog_entry_comment_approve_url(@blog, @entry, comment), :method => :patch, :data => { :confirm => 'Are you sure this comment approve?' }
        %td= link_to 'Destroy', [@blog, @entry, comment] , :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

%h2 New comment

= form_for([@blog, @entry, @comment]) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this entry from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :body
    = f.text_area :body
  = f.hidden_field :blog_id,   value: @blog.id
  = f.hidden_field :entry_id,  value: @entry.id
  .actions
    = f.submit 'Save'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogStudy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>